# Generated by Django 4.1.3 on 2022-11-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
