# Generated by Django 4.1.3 on 2022-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msms', '0002_admin_school_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='availability',
            field=models.CharField(default='[false, false, false, false, false, false, false]', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='availability',
            field=models.CharField(default='[false, false, false, false, false, false, false]', max_length=10),
        ),
    ]
