# Generated by Django 4.1.3 on 2022-12-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msms', '0004_alter_student_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='availability',
            field=models.CharField(default='[true, true, true, true, true, true, true]', max_length=70),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='availability',
            field=models.CharField(default='[true, true, true, true, true, true, true]', max_length=70),
        ),
    ]
