# Generated by Django 4.1.3 on 2022-12-01 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('number', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lessons', models.IntegerField()),
                ('interval', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('duration', models.DurationField()),
                ('state', models.CharField(choices=[('R', 'request'), ('B', 'booking'), ('C', 'cancelled')], default='R', max_length=20)),
                ('first_lesson_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('I', 'incoming'), ('P', 'processed')], default='I', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_transferred', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
