# Generated by Django 4.1.3 on 2022-12-08 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lessons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('number', models.CharField(max_length=60)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lessons', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('interval', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('duration', models.DurationField(choices=[(datetime.timedelta(seconds=1800), datetime.timedelta(seconds=1800)), (datetime.timedelta(seconds=2700), datetime.timedelta(seconds=2700)), (datetime.timedelta(seconds=3600), datetime.timedelta(seconds=3600))], default=30)),
                ('state', models.CharField(choices=[('R', 'request'), ('B', 'booking'), ('C', 'cancelled')], default='R', max_length=20)),
                ('first_lesson_date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=lessons.models.current_day, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_transferred', models.DateField(default=django.utils.timezone.now)),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.invoice')),
            ],
        ),
    ]
