# Generated by Django 4.1.3 on 2022-12-04 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_invoice_remaining_cost_alter_lesson_num_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), datetime.timedelta(seconds=1800)), (datetime.timedelta(seconds=2700), datetime.timedelta(seconds=2700)), (datetime.timedelta(seconds=3600), datetime.timedelta(seconds=3600))], default=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='interval',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='num_lessons',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
