# Generated by Django 4.1.3 on 2022-11-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_school_student_alter_user_urn_teacher_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('admin', 'admin'), ('superadmin', 'superadmin'), ('director', 'director'), ('siteadmin', 'siteadmin')], default='student', max_length=20),
        ),
    ]
