# Generated by Django 4.1.3 on 2022-11-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='availability',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='availability',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
