# Generated by Django 4.1.3 on 2022-12-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msms', '0005_alter_student_availability_and_more'),
        ('lessons', '0007_alter_lesson_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msms.teacher'),
        ),
    ]
