# Generated by Django 4.1.3 on 2022-11-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_student_availability_alter_student_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='URN',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
