# Generated by Django 4.1.3 on 2022-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_user_urn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='URN',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
