# Generated by Django 4.1.3 on 2022-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='schoolID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
