# Generated by Django 4.1.3 on 2022-11-26 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_alter_school_schoolid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lessons', models.IntegerField()),
                ('interval', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('duration', models.DurationField()),
                ('state', models.CharField(choices=[('R', 'request'), ('B', 'booking'), ('C', 'cancelled')], default='request', max_length=20)),
                ('first_lesson_date', models.DateField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.student')),
            ],
        ),
    ]
