# Generated by Django 4.1.3 on 2022-11-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_lesson_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
