# Generated by Django 4.1.3 on 2022-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='state',
            field=models.CharField(choices=[('R', 'request'), ('B', 'booking'), ('C', 'cancelled')], default='R', max_length=20),
        ),
    ]
