# Generated by Django 4.1.3 on 2022-11-26 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_alter_lesson_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('I', 'incoming'), ('C', 'confirmed')], default='I', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_transferred', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
