# Generated by Django 4.1.3 on 2022-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='state',
            field=models.CharField(choices=[('I', 'incoming'), ('P', 'processed')], default='I', max_length=20),
        ),
    ]
